
M	EQU	Byte Ptr 0[BX]
; VTL2.ASM
; --------
; MITS VTL-2 -- A Very Tiny Language for the Altair 8800
; by Frank McCoy, Copyright 1976
; (Retyped by Emmanuel ROCHE.)
; Modifications and simple CP/M port by Peter Schorn, 2006
; Changes to original Altair version
; - removed all IN/OUT to Altair ports and replaced by CP/M console I/O
; - system variables ^ (uparrow), , (comma) and . (period) which deal
;   with Altair I/O specialties were removed
; - added initialization code for & (start of user program)
; - added initialization code for * (memory size)
; - moved variable storage from predefined addresses after code,
;   requiring minor change to convp
; - modified decimal print routine to deal with powers of ten table
;   where low byte comes before high byte
; Tips
; - to return to CP/M type ">=<return>"
; - to delete the user program type "&=1353<return>"
;   (initial value of the system variable &)
;--------------------------------
; ASCII characters used (ASR-33 Teletype).
ctrlC	EQU	03H			; Abort key
backs	EQU	08H			; Backspace
lf	EQU	0AH			; Line Feed
cr	EQU	0DH			; Carriage Return
quote	EQU	22H			; Surrounds strings
dolar	EQU	24H			; Dollar
Lparen	EQU	28H			; Left	parenthesis
Rparen	EQU	29H			; Right parenthesis
star	EQU	2AH			; Multiplication
plus	EQU	2BH			; Addition
minus	EQU	2DH			; Subtraction
slash	EQU	2FH			; Division
zero	EQU	30H			; Number zero
colon	EQU	3AH			; Start of array statement
semicol	EQU	3BH			; Semicolon after PRINT
equal	EQU	3DH			; Equal sign
greatR	EQU	3EH			; Greater sign
quest	EQU	3FH			; Question mark
atsign	EQU	40H			; Discard line
; CP/M constants
BDOS	EQU	0005H
CONSTAT	EQU	0BH			; Console status
CONIN	EQU	01H			; Console input
CONOUT	EQU	02H			; Console output
bufsiz	EQU	73			; Size of input buffer
brkpnt	EQU	0000H			; Address of RST 0
;--------------------------------
;	User program
;--------------------------------
	ORG	0100H
begin:	MOV	BX,(Offset prgm)	; Initialize SV for next byte of
	MOV	Word Ptr ampers,BX	;	User program
; Can also restart here (0106) to keep user program
	MOV	BX,Word Ptr .BDOS+1	; Get end of TPA
	MOV	DX,0FC00H
	ADD	BX,DX			; Subtract space for stack
	MOV	Word Ptr asterix,BX	; Store in SV for memory size in bytes
start:	MOV	BX,Word Ptr .BDOS+1	; Get end of TPA
	MOV	BL,0			; Clear lower part
	MOV	SP,BX			; Initialize stack pointer
	XOR	AL,AL			; Initialize delimiter
	MOV	BX,(Offset okm)		; Point to "OK" prompt
	CALL	strng			; Display it on terminal
; Main loop of VTL-2 interpreter.
loop:	MOV	BX,0000H		; = 0
	MOV	Word Ptr dollar,BX	; Initialize char ptr
	CALL	cvtln			; Was a line number inputted?
	JNAE	L_1	
	JMP	stmnt			; 0: List (display) user program statements
L_1:
	CALL	exec			; No: Execute direct statement
	JZ	start			; Done: Return to interpreter
loop2:	CALL	find			; No: Find what remains in line?
; Start processing "=" statements.
eqstrt:	JNB	start			; No: Return to interpreter
	CALL	lxhn			; Get line number, and compare with ?
	MOV	Word Ptr dollar,BX	; Save char ptr
	MOV	BX,Word Ptr number	; Get lin ptr
	LAHF
	INC	BX
	SAHF
	LAHF				; 3 bytes = line number + space?
	INC	BX
	SAHF
	LAHF
	INC	BX
	SAHF
	CALL	exec			; Execute direct statement
	XCHG	BX,DX
	JZ	loop3			; Zero: ?
	MOV	BX,Word Ptr number	; Get lin ptr
	CALL	lxhn			; Get line number, and compare with ?
	JZ	loop3			; Zero: ?
	LAHF
	INC	BX
	SAHF
	MOV	Word Ptr exclam,BX	; RETURN value
	JMPS	loop2			; Unconditional jump to loop2
loop3:	PUSH	BX			; Save line number
	MOV	BX,Word Ptr ampers	; Next byte of user program
	MOV	CH,BH
	MOV	CL,BL			; Copy it into BC
	POP	BX			; Restore line number
	CALL	fnd3			; Find what?
	JMPS	eqstrt			; Process "=" statement
;--------------------------------
; Get line number from user program.
lxhn:	MOV	AL,M
	INC	BX
	MOV	BH,M
	MOV	BL,AL
; ... and falls through
; Compare HL with DE.
cphd:	MOV	AL,BL
	CMP	AL,DL
	JZ	L_2
	RET
L_2:
	MOV	AL,BH
	CMP	AL,DH
	RET
;--------------------------------
; Execute direct statements.
exec:	MOV	Word Ptr linumb,BX	; Save line number?
	CALL	var2
	INC	BX
	MOV	AL,M
	CALL	evil
	MOV	BX,Word Ptr dollar	; Get char ptr
	MOV	AL,BH			; 16-bits test if it is zero
	OR	AL,BL			; (Sets Zero flag)
	RET
;--------------------------------
; List (display) user program statements.
stmnt:	MOV	Word Ptr curent,BX	; Save current line number
	MOV	BL,CL			; Copy BC (?) to HL
	MOV	BH,CH
	MOV	Word Ptr dollar,BX	; And save it in char ptr
	MOV	AL,CH			; 16-bits test if BC is zero
	OR	AL,CL
	JZ	L_3	
	JMP	skp2			; No: Skip what?
L_3:
	MOV	BX,Word Ptr ampers	; Next byte of user program
	XCHG	BX,DX			; Put it in DE
	MOV	BX,(Offset prgm)	; Start of user program
; List (display) program on terminal.
lst2:	CALL	cphd			; Check if next = start (= no program)
	JNZ	L_4	
	JMP	start			; Yes: Return to interpreter
L_4:
	PUSH	DX			; No:
	MOV	CL,M
	LAHF				; Get line number from memory
	INC	BX
	SAHF
	MOV	CH,M			;   and put it into BC.
	PUSH	BX
	CALL	prnt2			; Print 16-bit line number in decimal
	POP	BX
	LAHF				; Skip the space
	INC	BX
	SAHF
	CALL	pntmsg			; Print contents of line
	CALL	crlf			; End of line
	POP	DX
	JMPS	lst2			; Loop until end of program
;--------------------------------
; Next text?
nxtxt:	MOV	BX,Word Ptr number	; Lin ptr
	INC	BX
lookag:	INC	BX
	MOV	AL,M
	AND	AL,AL
	JNZ	lookag			; Look again...
; "Output a char" (at the end) uses those 2 instructions...
outd:	LAHF
	INC	BX
	SAHF
	RET
find:	MOV	BX,Word Ptr ampers	; Next byte of user program
	MOV	CL,BL
	MOV	CH,BH			; Copy it to BC
	MOV	BX,Word Ptr dollar	; Char ptr
	XCHG	BX,DX			; Copy it to DE
	MOV	BX,(Offset prgm)	; PC of user program
fnd2:	MOV	Word Ptr number,BX	; Set it equal to lin ptr
	MOV	AL,CL
	CMP	AL,BL			; Compare low byte of user program
	JNZ	nxtuu
	MOV	AL,CH			; Compare high byte of user program
	CMP	AL,BH
	JNZ	L_5	
	RET				; Zero: Return
L_5:
; Not zero: ?
nxtuu:	MOV	AL,M			; Get low byte of user program
	SUB	AL,DL			; Subtract low byte of char ptr
	INC	BX			; Point to next byte
	MOV	AL,M			; Get high byte of user program
	SBB	AL,DH			; Subtract low byte of char ptr
	LAHF				; Point to previous byte
	DEC	BX
	SAHF
	CMC				; Complement Carry flag
	JNB	L_6	
	RET				; Return if DE > M(HL)
L_6:
; Else, call ?
fnd3:	CALL	nxtxt
	JMPS	fnd2
evil:	CMP	AL,quote		; Is it a quote surrounding strings?
	JNZ	L_7	
	JMP	quote2			; Yes: go process it
L_7:
	CALL	eval			; No: Evaluate expression
	PUSH	CX
	MOV	BX,Word Ptr linumb
	CALL	convp
	POP	CX
	CMP	AL,dolar		; Is it a single character?
	JNZ	andt			; No: Check if it is a "?" char
	MOV	AL,CL			; Yes:
	JMP	outch			;   Output it to terminal
; It is not a single char. Is it followed by a "?" char?
andt:	SUB	AL,greatR+1
	JNZ	L_8	
	JMP	prnt2			; Yes: Display the line number in decimal
L_8:
; System Variable "Greater Than" subroutine.
; Pass a 16-bits value in BC to a machine language subroutine.
	INC	AL			; Is it a ">" char?
	JNZ	L_9	
	MOV	CL,0			; Call RST 0 at 0000H
	MOV	DL,0
	INT	224
L_9:
; "At the conclusion of the machine language subroutine,
; a Intel 8080 RET instruction returns control to VTL-2,
; and places the value found in the BC register pair into
; the question variable ">".
	MOV	M,CL			; Copy BC to M(HL)
	INC	BX
	MOV	M,CH
	MOV	BX,(Offset greater)	; Point to ">" data storage
	MOV	AL,M			; Get 1st byte from memory
	ADD	AL,CL			; Add C-reg
	MOV	CL,AL			; Move it to C-reg
	DEC	BX			; Point to previous byte
	MOV	AL,M			; Get 2nd byte from memory
	ADC	AL,CH			; Add B-reg
	MOV	M,CL			; Move C-reg to ">" data storage
	INC	BX			; Go back to 1st byte
	MOV	M,AL			; Move B-reg to ">" data storage
; Compare BC with DE.
cpbd:	MOV	AL,CL			; BC = ">" data storage
	CMP	AL,DL
	JZ	L_10
	RET
L_10:
	MOV	AL,CH			; DE = ?
	CMP	AL,DH
	RET
;--------------------------------
; Skip what?
skp2:	CALL	find
	JNB	insrt
	CALL	lxhn			; Get line number from user program,
;				    and compare with ?
	JNZ	insrt			; Not zero: Insert
	CALL	nxtxt
	XCHG	BX,DX
	MOV	BX,Word Ptr number	; Lin ptr
delt:	CALL	cpbd			; Compare BC with DE
	JZ	fitit			; Equal: ?
; Not equal: ?
	MOV	SI,DX			; Move byte at M(DE)
	MOV	AL,[SI]
	MOV	M,AL			;   to M(HL).
	LAHF				; Increment HL
	INC	BX
	SAHF
	LAHF				; Increment DE
	INC	DX
	SAHF
	JMPS	delt			; Loop
; Insert a program line in program "text".
fitit:	MOV	Word Ptr ampers,BX	; Save address of next byte of user program
	MOV	CH,BH			; Copy HL to BC
	MOV	CL,BL
insrt:	MOV	BX,Word Ptr curent
	MOV	DX,0003H		; 3 = line number + space?
	MOV	AL,M			; Get byte
	AND	AL,AL			; Is it zero?
	JNZ	L_11	
	JMP	loop			; Yes: Back to main loop of interpreter
L_11:
cntln:	INC	DX			; No:
	INC	BX
	MOV	AL,M			; Get next byte
	AND	AL,AL
	JNZ	cntln			; Not zero: Back to main loop of interpreter
; Zero: ?
	XCHG	BX,DX
	ADD	BX,CX			; Add BC
	XCHG	BX,DX			; Put result in DE
	MOV	BX,(Offset asterix)	; Memory size
	MOV	AL,DL			; Subtract memory size from program length?
	SUB	AL,M
	INC	BX
	MOV	AL,DH
	SBB	AL,M
	JNAE	L_12	
	JMP	start			; No memory: Return to interpreter
L_12:
; Some memory is present.
	XCHG	BX,DX
	MOV	Word Ptr ampers,BX	; Then, this must be next byte of user PGM?
	LAHF
	INC	CX
	SAHF
	LAHF
	INC	BX
	SAHF
	PUSH	BX
	MOV	BX,Word Ptr number	; Lin ptr
	XCHG	BX,DX
	POP	BX
slide:	LAHF
	DEC	CX
	SAHF
	LAHF
	DEC	BX
	SAHF
	MOV	SI,CX			; A = M(BC)
	MOV	AL,[SI]
	MOV	M,AL
	CALL	cpbd			; Compare ? with ?
	JNZ	slide			; Move program "text"
	MOV	BX,Word Ptr dollar	; Char ptr
	MOV	AL,BL			; Get M(HL)
	MOV	SI,CX			; M(BC) = A
	MOV	[SI],AL
	INC	CX			; Increment BC
	MOV	AL,BH			; Get M(HL)
	MOV	SI,CX			; M(BC) = A
	MOV	[SI],AL
	MOV	BX,Word Ptr curent
	DEC	BX			; Decrement it?
; Move one line in memory?
movl:	INC	BX
	INC	CX
	MOV	AL,M
	MOV	SI,CX			; M(BC) = A
	MOV	[SI],AL
	AND	AL,AL
	JNZ	movl			; Not zero: Loop
	JMP	loop			; Zero: Back to main loop of interpreter
;--------------------------------
; Print 16-bit line number in decimal.
prnt2:	MOV	DX,(Offset decbuf)	; Decimal buffer (5 chars long)
	MOV	BX,(Offset pwrs10)	; Table of decimal values
cvd1:	PUSH	DX			; Save address of DECBUF on Stack
	MOV	DH,CH			; Copy BC to DE
	MOV	DL,CL
	MOV	CL,M			; Get low byte of dec value
	INC	BX
	MOV	CH,M			; Get high byte of dec value
	INC	BX
	PUSH	BX			; Save address of next word
	XCHG	BX,DX
	CALL	div			; 16-bits division
	XCHG	BX,DX
	MOV	AL,BL			; Get low byte
	MOV	CH,DH			; Copy DE to BC
	MOV	CL,DL
	POP	BX			; Restore address of next dec value
	POP	DX			; Restore address of DECBUF
	ADD	AL,zero			; Make it an ASCII number
	MOV	SI,DX			; M(DE) = A
	MOV	[SI],AL
	INC	DX
	MOV	AL,M			; Get high byte
	CMP	AL,7EH			; "~" ?
	JNZ	cvd1			; No: Loop
; Yes: ?
	MOV	BX,(Offset decbuf)-1	; Point before decimal buffer
	DEC	DX
	MOV	SI,DX			; A = M(DE)
	MOV	AL,[SI]
	OR	AL,10000000B		; Why?
	MOV	SI,DX			; M(DE) = A
	MOV	[SI],AL
; Suppress zeroes?
zrsup:	INC	BX			; Point to next char
	MOV	AL,M			; Get it
	CMP	AL,zero			; Is it an ASCII zero?
	JZ	zrsup			; Yes: Loop, not showing zeroes
; Print message -- Init delimiter.
pntmsg:	XOR	AL,AL			; Init delimiter
; Start displaying a message.
strtmsg:MOV	Byte Ptr delim,AL	; Save delimiter
	MOV	CH,AL			;    and put it in B-reg.
outmsg:	MOV	AL,M			; Get char from memory
	INC	BX			; Update memory pointer
	CMP	AL,CH			; Is it the delimiter?
	JZ	contC			; Yes: Check if it is Ctrl-C
	CALL	ascii			; No: Display the char on the terminal
	JMPS	outmsg			;    and loop until delimiter found.
; Check for Control-C.
contC:	CALL	polcat			; Poll character at terminal?
	JNAE	L_13	
	RET				; None available: Return
L_13:
	CALL	inch			; One char present: Get it
	CMP	AL,ctrlC		; Is it Control-C?
	JNZ	L_14	
	JMP	start			; Yes: Return to interpreter
L_14:
	JMP	inch			; No: Get char
;--------------------------------
; Evaluate expressions between parentheses.
eval:	CALL	getval			; Get value of a number
; Next term of an expression?
nxtrm:	MOV	AL,M
	AND	AL,AL			; Number = zero?
	JNZ	L_15	
	RET				; Yes: Return
L_15:
	CMP	AL,Rparen		; No: Is it a closing parenthesis?
	JNZ	L_16	
	JMP	outd			; Yes: INC HL and return
L_16:
	CALL	term			; No: Process term of expression
	MOV	CH,BH			; Copy HL to BC
	MOV	CL,BL
	MOV	BX,Word Ptr evalptr	; Load eval pointer
	JMPS	nxtrm			;    and loop until 00H found.
;--------------------------------
; Process one term of an arithmetic expression.
term:	PUSH	CX			; Put BC on Stack
	MOV	AL,M			; Get char
	LAHF				; Save it on Stack
	XCHG	AL,AH
	PUSH	AX
	XCHG	AL,AH
	LAHF				; Point to next char
	INC	BX
	SAHF
	CALL	getval			; Get value of a decimal number
	MOV	Word Ptr evalptr,BX	; Save eval pointer?
	POP	AX			; Restore char
	XCHG	AL,AH
	POP	BX			; Place BC into HL
; Is it followed by an addition?
	CMP	AL,plus
	JNZ	eval2			; No: Check next arithmetic operation
; Yes: 16-bit addition.
	LAHF				; Add BC to HL
	ADD	BX,CX
	RCR	SI,1
	SAHF
	RCL	SI,1
	RET				; Result in HL
;--------------------------------
; Is it followed by a subtraction?
eval2:	CMP	AL,minus
	JNZ	eval3			; No: Check next arithmetic operation
; Yes: 16-bit subtraction subroutine.
hsubb:	MOV	AL,BL			; Subtract BC from HL
	SUB	AL,CL
	MOV	BL,AL
	MOV	AL,BH
	SBB	AL,CH
	MOV	BH,AL
	RET				; Result in HL
;--------------------------------
; Is it followed by a multiplication?
eval3:	CMP	AL,star
	JNZ	eval4			; No: Check next arithmetic operation
; Yes: 16-bit multiplication subroutine.
	XCHG	BX,DX			; Put multiplicand in DE
	MOV	BX,0000H		; Clear partial product
	MOV	AL,10H			; Set loop count to 16 bits
mult1:	LAHF				; Save it on Stack
	XCHG	AL,AH
	PUSH	AX
	SHL	BX,1			; Add to product
	XCHG	BX,DX			; Put it into DE
	SHL	BX,1			; Add to product
	XCHG	BX,DX			; Put it into HL
	JNB	mult2			; If the result has 17 bits,
	ADD	BX,CX			;   add multiplier to product.
mult2:	POP	AX			; Restore count
	XCHG	AL,AH
	SAHF
	DEC	AL			; Decrement it
	JNZ	mult1			; Not end: Loop
	RET				; Result in HL
;--------------------------------
; Is it followed by a division?
eval4:	CMP	AL,slash
	JNZ	eval5			; No: Now, check relational operators
	CALL	div			; Yes: Use a subroutine
	MOV	Word Ptr percent,BX	; Remainder of divide operation
	XCHG	BX,DX
	RET				; Result in HL
;--------------------------------
; 16-bit division subroutine.
; BC: divisor, DE: dividend, HL: remainder
div:	XCHG	BX,DX			; Put dividend in DE
	MOV	BX,0000H		; Initialize remainder in HL
	MOV	AL,CH			; Checks if 16-bits divisor = zero
	OR	AL,CL
	JNZ	L_17	
	RET				; Yes: Return (division by zero is forbidden)
L_17:
	MOV	AL,10H			; Set loop count to 16 bits
div1:	LAHF				; Save it on Stack
	XCHG	AL,AH
	PUSH	AX
	SHL	BX,1
	XCHG	BX,DX			; Dividend
	SHL	BX,1			;   bit
	XCHG	BX,DX			;   to Carry.
	JNB	div2			; It was zero
	INC	BX			; It was one, duplicate in HL
div2:	CALL	hsubb			; Subtract BC from HL
	INC	DX
	JNB	div3			; It was zero
	ADD	BX,CX			; Add divisor to remainder
	DEC	DX
div3:	POP	AX			; Restore loop count
	XCHG	AL,AH
	SAHF
	DEC	AL			; Decrement it
	JNZ	div1			; Not end: Loop
	RET
;--------------------------------
; Now, check the relational operators.
eval5:	MOV	DX,0000H		; Init DE with FALSE value
	CALL	evil5			; Check the relational operators
	XCHG	BX,DX			; HL will contain the TRUE/FALSE value
	RET
;--------------------------------
; Is it followed by an equality?
evil5:	SUB	AL,equal
	JNZ	evil6			; No: Check next relational operators
	CALL	hsubb			; Yes: Use a subroutine
	JZ	L_18	
	RET				; Return if not zero
L_18:
	OR	AL,BL			; Is it zero?
	JZ	L_19	
	RET				; No: Return if not zero (FALSE)
L_19:
	LAHF				; Yes: = 1 (TRUE value)
	INC	DX
	SAHF
	RET
;--------------------------------
; Is it followed by a greater than?
evil6:	DEC	AL			; "=" - 1 = "<"
	JZ	evil7			; Yes: Check next relational operator
	CALL	hsubb			; No: Use a subroutine
	JNAE	L_20	
	RET				; Return if FALSE
L_20:
	LAHF				; = 1 (TRUE value)
	INC	DX
	SAHF
	RET
;--------------------------------
; Is it followed by a less than?
evil7:	CALL	hsubb			; Use a subroutine
	JNB	L_21	
	RET				; Return if FALSE
L_21:
	LAHF				; = 1 (TRUE value)
	INC	DX
	SAHF
	RET
;--------------------------------
; Get value of a decimal number.
getval:	CALL	cvbin			; Convert to binary number
	JNAE	L_22	
	RET				; It was a number: Return
L_22:
	CMP	AL,quest		; Is it a PRINT statement?
	LAHF				; Increment mem ptr
	INC	BX
	SAHF
	JNZ	var			; No: Check if it is a variable name
; Yes: ?
	MOV	Word Ptr valvar,BX	; Save value of variable?
	CALL	inln
	CALL	eval			; Evaluate expression
	MOV	BX,Word Ptr valvar	; Value of expression?
	RET
;--------------------------------
; Is it a variable name?
var:	CMP	AL,dolar		; Is it an INPUT statement?
	JNZ	var1			; No: Check next possibility
	CALL	inch			; Yes: Input next char
	MOV	CL,AL
	MOV	CH,00H			; Make sure a char is a byte value
	RET
; Is it the start of an expression?
var1:	CMP	AL,Lparen
	JNZ	L_23	
	JMP	eval			; Yes: Evaluate expression
L_23:
	LAHF				; No: Re-point to character
	DEC	BX
	SAHF
var2:	CALL	convp
	MOV	CL,M
	LAHF
	INC	BX
	SAHF
	MOV	CH,M
	MOV	BX,Word Ptr result
	RET
;--------------------------------
; Obviously, deal with array DEEK/DOKE...
array:	CALL	eval			; Evaluate expression
	MOV	Word Ptr result,BX	; Save result of evaluation?
	MOV	BX,Word Ptr ampers	; Get address of next byte of user program
	ADD	BX,CX
	ADD	BX,CX
	POP	AX
	XCHG	AL,AH
	SAHF
	RET
;--------------------------------
; Convert p...?
convp:	MOV	AL,M
	LAHF
	INC	BX
	SAHF
	LAHF
	XCHG	AL,AH
	PUSH	AX
	XCHG	AL,AH
	CMP	AL,colon		; Is it the start of an array statement?
	JZ	array			; Yes: Go to ARRAY subroutine
; No: ?
	MOV	Word Ptr result,BX	; Save value of expression
	AND	AL,00111111B		; = 3FH
	ADD	AL,AL			; duplicate A
	ADD	AL,(Offset vars) AND 0FFH	; make sure that no carry occurs
	MOV	BL,AL			; lower part
	MOV	BH,(Offset vars) SHR 8	; HL now points to variable
	POP	AX
	XCHG	AL,AH
	SAHF
	RET
L_24	EQU	$
	DSEG
	ORG	Offset L_24
;--------------------------------
; Table of powers of 10.
pwrs10	DW	10000
	DW	1000
	DW	100
	DW	10
	DW	1
L_25	EQU	$
	CSEG
	ORG	Offset L_25
;--------------------------------
; Test if it is an ASCII decimal number character.
tstn:	MOV	AL,M			; Get char
	CMP	AL,'9'+1		; Is it > "9" ?
	CMC
	JNB	L_26
	RET
L_26:
	CMP	AL,'0'			; Is it < "0" ?
	RET
;--------------------------------
; Convert to line number.
cvtln:	CALL	inln
; Convert to binary number.
cvbin:	CALL	tstn			; Is it a number?
	JNB	L_27	
	RET				; No: Return
L_27:
; Yes: Convert the ASCII char to binary number.
	MOV	CX,0000H
cbloop:	MOV	AL,M			; Get char
	SUB	AL,zero			; Convert from ASCII to binary
	ADD	AL,CL			; Add C-reg
	MOV	CL,AL			; Put result in C-reg
	MOV	AL,00H			; Re-init A-reg
	ADC	AL,CH			; Add B-reg
	MOV	CH,AL			; Put result in B-reg
	LAHF				; Point to next char
	INC	BX
	SAHF
	CALL	tstn			; Is it a number?
	CMC
	JNAE	L_28	
	RET				; No: Return
L_28:
; Yes: ?
	PUSH	BX			; Save pointer
	MOV	BH,CH			; Copy BC to HL
	MOV	BL,CL
	SHL	BX,1			; 2 times HL
	SHL	BX,1			; 4 times HL
	ADD	BX,CX			; 2 times BC
	SHL	BX,1			; 8 times HL
	MOV	CH,BH			; Move HL to BC ?
	MOV	CL,BL
	POP	BX			; Restore pointer
	JMPS	cbloop			; Loop until not a number
;--------------------------------
; Process line input from terminal.
inln6:	CMP	AL,atsign		; Discard line inputted?
	JZ	newlin			; Yes: Start a new line
; No: We are in a line. Are we at the end?
	INC	BX			; Increment line pointer
	MOV	AL,BL			; Get its low byte
	CMP	AL,((Offset linbuf)+(Offset bufsiz)) AND 0FFH	; Are we at the end of the line?
	JNZ	inln2			; No: Get next char
; Yes: Start a new line on the terminal.
newlin:	CALL	crlf			; Return "cursor" at beginning of next line
inln:	MOV	BX,(Offset linbuf)+1	; Point to first char in line buffer
; Check if we reached the beginning of the line,
; that is to say: erased all the line, backspacing chars.
inln5:	DEC	BX			; Point before the first char
	MOV	AL,BL
	CMP	AL,((Offset linbuf)-1) AND 0FFH	; Is it the end of the line?
	JZ	newlin			; Yes: Start a new line
; Not at end of line: Get another char, and check it.
inln2:	CALL	inch			; Input another char
	MOV	M,AL
	CMP	AL,backs		; Backspace to erase a char?
	JZ	inln5			; Yes: Check if we erased everything
; No: Check if the user had ended inputting a line.
	CMP	AL,cr
	JB	inln2			; No: Get another char
	JNZ	inln6			; Yes: Go proceed another line
	XOR	AL,AL			; Mark end of line with a 00H
	MOV	M,AL
	MOV	BX,(Offset linbuf)	; Why?
	JMPS	prlf			; It was CR: add LF
;--------------------------------
quote2:	INC	BX			; Skip beginning quote
strng:	CALL	strtmsg			; Proceed start of string
	MOV	AL,M			; Get char
	CMP	AL,semicol		; Is it a semicolon?
	JNZ	L_29	
	RET				; Yes: Then, no cr/lf after PRINT
L_29:
; No: End of line reached, output CR and LF.
crlf:	MOV	AL,cr			; Carriage Return
	CALL	outch
prlf:	MOV	AL,lf			; Line Feed
	CALL	outch
	RET
L_30	EQU	$
	DSEG
	ORG	Offset L_30
;--------------------------------
okm	DB	cr,lf
	DB	'OK',00H
L_31	EQU	$
	CSEG
	ORG	Offset L_31
; carry set iff character is available
polcat:	PUSH	BX
	PUSH	DX
	PUSH	CX
	MOV	CL,CONSTAT		; Get console status
	INT	224			; A=0FFH if character available else A=0
	ROR	AL,1
	JMPS	done
; return the next character in A
inch:	PUSH	BX
	PUSH	DX
	PUSH	CX
	MOV	CL,CONIN		; Console input
	INT	224
	AND	AL,7FH
	JMPS	done
; Output character in A, optionally clearing highest bit
ascii:	AND	AL,7FH
outch:	PUSH	BX
	PUSH	DX
	PUSH	CX
	LAHF
	XCHG	AL,AH
	PUSH	AX
	XCHG	AL,AH
	MOV	DL,AL
	MOV	CL,CONOUT		; Console output
	INT	224
	POP	AX
	XCHG	AL,AH
	SAHF
done:	POP	CX
	POP	DX
	POP	BX
	RET
L_32	EQU	$
	DSEG
	ORG	Offset L_32
vars	RS	62			; @, A - Z
number	RS	4
exclam	RS	4			; 
dollar	RS	4			; $
percent	RS	2			; %
ampers	RS	3			; &
greater	RS	5			; >
asterix	RS	12			; *
evalptr	RS	12
result	RS	2
linumb	RS	2
curent	RS	2
valvar	RS	12
decbuf	RS	4+1
delim	RS	1
linbuf	RS	bufsiz
prgm	EQU	(Offset $)
	END
